defaults:
  - agent: td3
  - obs_type_params: states
  - override hydra/launcher: submitit_local

# unsupervised exploration
expl_agent: proto
# task settings
task: walker_walk
discount: 0.99
# train settings
num_grad_steps: 500000
log_every_steps: 1000
# eval
eval_every_steps: 10000
num_eval_episodes: 10
# dataset
# replay_buffer_dir: ../../../datasets # make sure to update this if you change hydra run dir
replay_buffer_dir: /code/exorl/datasets # make sure to update this if you change hydra run dir
replay_buffer_size: 2000000
replay_buffer_num_workers: 4
batch_size: ${obs_type_params.batch_size}
# misc
seed: 1
device: cuda
save_video: true
use_tb: false

relable: false
frame_stack: 3


hydra:
  run:
    dir: /code/exorl/output/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}

